import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import Router from 'next/router';
import { useEffect } from 'react';

import { addEnv } from '../store/UsersSlice';
const Home: NextPage = () => {

  useEffect(()=> {
    const ee = Router.pathname;
  if (ee === '/') {
      Router.push('/pizzas')
  }
  }, [

  ])

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
       
      </Head>

      <main className={styles.main}>
      
      </main>

      
    </div>
  );
};



export default Home;

